<?php

namespace OOP;

class Teacher extends User
{
    protected $type;
    protected $email;
    protected $name;
    protected $phone;

    public function __construct($name, $email, $phone, $type)
    {
        parent::__construct($name, $email, $phone, $type);
        $this->name = $name;
        $this->email = $email;
        $this->phone = $phone;
        $this->type = $type;

    }
        public function profile()
        {
            return parent::profile(); // TODO: Change the autogenerated stub
        }
}
